name: Build KeeTheft

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore KeeTheft/KeeTheft.sln
        
      - name: Build
        run: msbuild KeeTheft/KeeTheft.sln /p:Configuration=Release /p:Platform="Any CPU"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: KeeTheft
          path: KeeTheft/KeeTheft/bin/Release/KeeTheft.exe
